services:
  - type: web
    name: swimming-times-statistics
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 4 --bind 0.0.0.0:$PORT --timeout 120 webapp.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: webapp.app
      - key: PYTHONPATH
        value: /opt/render/project/src 
