services:
  - type: web
    name: swimming-times-statistics
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn webapp.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: webapp.app 